-- B1/B2 Lesen at full official length: 30 items each, official Teil sizes
-- Grounded against Goethe Zertifikat B1 / Goethe-Zertifikat B2 Modellsätze:
--   B1: T1 R/F ×6, T2 MCQ ×6 (2 Texte), T3 Anzeigen A–J ×7 (1 ohne Match),
--       T4 Ja/Nein ×7, T5 MCQ ×4  = 30 Aufgaben, 65 Minuten
--   B2: T1 4 Personen ×9, T2 MCQ ×6, T3 MCQ ×6, T4 Äußerung→Überschrift ×6,
--       T5 Paragraf→Überschrift ×3 = 30 Aufgaben, 65 Minuten

UPDATE test_modules tm
SET
  description = '5 Teile wie in der Prüfung: Richtig/Falsch, Pressetexte, Anzeigen zuordnen, Meinungen, Betriebsordnung. 30 Aufgaben, 65 Minuten.',
  question_count = 30,
  duration_minutes = 65
FROM levels l, skills s
WHERE tm.level_id = l.id AND tm.skill_id = s.id
  AND l.code = 'B1' AND s.code = 'reading';

UPDATE test_modules tm
SET
  description = '5 Teile wie in der Prüfung: Personen zuordnen, zwei Sachtexte, Äußerungen und Überschriften, Vertragstexte. 30 Aufgaben, 65 Minuten.',
  question_count = 30,
  duration_minutes = 65
FROM levels l, skills s
WHERE tm.level_id = l.id AND tm.skill_id = s.id
  AND l.code = 'B2' AND s.code = 'reading';

-- Replace B1 and B2 reading questions
DELETE FROM questions WHERE test_module_id IN (
  SELECT tm.id FROM test_modules tm
  JOIN levels l ON tm.level_id = l.id
  JOIN skills s ON tm.skill_id = s.id
  WHERE l.code IN ('B1','B2') AND s.code = 'reading'
);

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Blogeintrag, Meine ersten Monate in der Klinik:\n\n„Seit drei Monaten arbeite ich als Pflegerin in Frankfurt. Am Anfang war die größte Hürde nicht die Arbeit selbst, sondern die Sprache: Die Übergaben am Morgen waren so schnell, dass ich nur die Hälfte verstanden habe. Meine Mentorin Sandra hat mir dann geraten, wichtige Fachbegriffe auf Karteikarten zu schreiben, das hat wirklich geholfen. Inzwischen übernehme ich eigene Patienten und fühle mich im Team akzeptiert. Nur an die Frühschichten um 6 Uhr habe ich mich noch immer nicht gewöhnt. Nächsten Monat beginne ich einen B2-Kurs, den meine Klinik bezahlt. Wenn alles klappt, möchte ich mich in zwei Jahren zur Stationsleitung weiterbilden.“\n\nAussage: Die Autorin arbeitet seit drei Monaten in Frankfurt.', 'multiple_choice', '["Richtig", "Falsch"]'::jsonb, 'Richtig', 'Erster Satz: „Seit drei Monaten arbeite ich als Pflegerin in Frankfurt.“', 1, 1, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Blogeintrag, Meine ersten Monate in der Klinik:\n\n„Seit drei Monaten arbeite ich als Pflegerin in Frankfurt. Am Anfang war die größte Hürde nicht die Arbeit selbst, sondern die Sprache: Die Übergaben am Morgen waren so schnell, dass ich nur die Hälfte verstanden habe. Meine Mentorin Sandra hat mir dann geraten, wichtige Fachbegriffe auf Karteikarten zu schreiben, das hat wirklich geholfen. Inzwischen übernehme ich eigene Patienten und fühle mich im Team akzeptiert. Nur an die Frühschichten um 6 Uhr habe ich mich noch immer nicht gewöhnt. Nächsten Monat beginne ich einen B2-Kurs, den meine Klinik bezahlt. Wenn alles klappt, möchte ich mich in zwei Jahren zur Stationsleitung weiterbilden.“\n\nAussage: Die größte Schwierigkeit am Anfang war die Pflegearbeit selbst.', 'multiple_choice', '["Richtig", "Falsch"]'::jsonb, 'Falsch', 'Die größte Hürde war die Sprache, nicht die Arbeit selbst.', 2, 1, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Blogeintrag, Meine ersten Monate in der Klinik:\n\n„Seit drei Monaten arbeite ich als Pflegerin in Frankfurt. Am Anfang war die größte Hürde nicht die Arbeit selbst, sondern die Sprache: Die Übergaben am Morgen waren so schnell, dass ich nur die Hälfte verstanden habe. Meine Mentorin Sandra hat mir dann geraten, wichtige Fachbegriffe auf Karteikarten zu schreiben, das hat wirklich geholfen. Inzwischen übernehme ich eigene Patienten und fühle mich im Team akzeptiert. Nur an die Frühschichten um 6 Uhr habe ich mich noch immer nicht gewöhnt. Nächsten Monat beginne ich einen B2-Kurs, den meine Klinik bezahlt. Wenn alles klappt, möchte ich mich in zwei Jahren zur Stationsleitung weiterbilden.“\n\nAussage: Der Tipp mit den Karteikarten kam von ihrer Mentorin.', 'multiple_choice', '["Richtig", "Falsch"]'::jsonb, 'Richtig', '„Meine Mentorin Sandra hat mir dann geraten …“', 3, 1, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Blogeintrag, Meine ersten Monate in der Klinik:\n\n„Seit drei Monaten arbeite ich als Pflegerin in Frankfurt. Am Anfang war die größte Hürde nicht die Arbeit selbst, sondern die Sprache: Die Übergaben am Morgen waren so schnell, dass ich nur die Hälfte verstanden habe. Meine Mentorin Sandra hat mir dann geraten, wichtige Fachbegriffe auf Karteikarten zu schreiben, das hat wirklich geholfen. Inzwischen übernehme ich eigene Patienten und fühle mich im Team akzeptiert. Nur an die Frühschichten um 6 Uhr habe ich mich noch immer nicht gewöhnt. Nächsten Monat beginne ich einen B2-Kurs, den meine Klinik bezahlt. Wenn alles klappt, möchte ich mich in zwei Jahren zur Stationsleitung weiterbilden.“\n\nAussage: Sie hat sich an die Frühschichten gewöhnt.', 'multiple_choice', '["Richtig", "Falsch"]'::jsonb, 'Falsch', '„… habe ich mich noch immer nicht gewöhnt.“', 4, 1, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Blogeintrag, Meine ersten Monate in der Klinik:\n\n„Seit drei Monaten arbeite ich als Pflegerin in Frankfurt. Am Anfang war die größte Hürde nicht die Arbeit selbst, sondern die Sprache: Die Übergaben am Morgen waren so schnell, dass ich nur die Hälfte verstanden habe. Meine Mentorin Sandra hat mir dann geraten, wichtige Fachbegriffe auf Karteikarten zu schreiben, das hat wirklich geholfen. Inzwischen übernehme ich eigene Patienten und fühle mich im Team akzeptiert. Nur an die Frühschichten um 6 Uhr habe ich mich noch immer nicht gewöhnt. Nächsten Monat beginne ich einen B2-Kurs, den meine Klinik bezahlt. Wenn alles klappt, möchte ich mich in zwei Jahren zur Stationsleitung weiterbilden.“\n\nAussage: Den B2-Kurs muss sie selbst bezahlen.', 'multiple_choice', '["Richtig", "Falsch"]'::jsonb, 'Falsch', '„… den meine Klinik bezahlt.“', 5, 1, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Blogeintrag, Meine ersten Monate in der Klinik:\n\n„Seit drei Monaten arbeite ich als Pflegerin in Frankfurt. Am Anfang war die größte Hürde nicht die Arbeit selbst, sondern die Sprache: Die Übergaben am Morgen waren so schnell, dass ich nur die Hälfte verstanden habe. Meine Mentorin Sandra hat mir dann geraten, wichtige Fachbegriffe auf Karteikarten zu schreiben, das hat wirklich geholfen. Inzwischen übernehme ich eigene Patienten und fühle mich im Team akzeptiert. Nur an die Frühschichten um 6 Uhr habe ich mich noch immer nicht gewöhnt. Nächsten Monat beginne ich einen B2-Kurs, den meine Klinik bezahlt. Wenn alles klappt, möchte ich mich in zwei Jahren zur Stationsleitung weiterbilden.“\n\nAussage: Sie möchte später Stationsleitung werden.', 'multiple_choice', '["Richtig", "Falsch"]'::jsonb, 'Richtig', '„… möchte ich mich … zur Stationsleitung weiterbilden.“', 6, 1, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Pressetext 1, Fachkräfte aus dem Ausland:\n\n„Deutsche Krankenhäuser werben zunehmend im Ausland um Personal. Besonders gefragt sind Pflegekräfte aus Ländern mit anerkannten Ausbildungsstandards. Der Verband der Klinikbetreiber fordert schnellere Anerkennungsverfahren, denn derzeit warten Bewerberinnen und Bewerber im Schnitt acht Monate auf ihren Bescheid. Einige Bundesländer testen deshalb digitale Antragsverfahren, mit denen sich die Wartezeit halbieren soll.“\n\nWorum werben deutsche Krankenhäuser laut Text?', 'multiple_choice', '["Um Personal aus dem Ausland", "Um mehr Patienten", "Um private Investoren"]'::jsonb, 'Um Personal aus dem Ausland', '„Deutsche Krankenhäuser werben zunehmend im Ausland um Personal.“', 7, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Pressetext 1, Fachkräfte aus dem Ausland:\n\n„Deutsche Krankenhäuser werben zunehmend im Ausland um Personal. Besonders gefragt sind Pflegekräfte aus Ländern mit anerkannten Ausbildungsstandards. Der Verband der Klinikbetreiber fordert schnellere Anerkennungsverfahren, denn derzeit warten Bewerberinnen und Bewerber im Schnitt acht Monate auf ihren Bescheid. Einige Bundesländer testen deshalb digitale Antragsverfahren, mit denen sich die Wartezeit halbieren soll.“\n\nWie lange dauert das Anerkennungsverfahren derzeit durchschnittlich?', 'multiple_choice', '["Acht Monate", "Vier Monate", "Zwei Jahre"]'::jsonb, 'Acht Monate', '„… warten … im Schnitt acht Monate auf ihren Bescheid.“', 8, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Pressetext 1, Fachkräfte aus dem Ausland:\n\n„Deutsche Krankenhäuser werben zunehmend im Ausland um Personal. Besonders gefragt sind Pflegekräfte aus Ländern mit anerkannten Ausbildungsstandards. Der Verband der Klinikbetreiber fordert schnellere Anerkennungsverfahren, denn derzeit warten Bewerberinnen und Bewerber im Schnitt acht Monate auf ihren Bescheid. Einige Bundesländer testen deshalb digitale Antragsverfahren, mit denen sich die Wartezeit halbieren soll.“\n\nWas sollen digitale Antragsverfahren bewirken?', 'multiple_choice', '["Die Wartezeit halbieren", "Die Ausbildung verkürzen", "Die Gehälter erhöhen"]'::jsonb, 'Die Wartezeit halbieren', '„… mit denen sich die Wartezeit halbieren soll.“', 9, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Pressetext 2, Vier-Tage-Woche im Test:\n\n„Ein Logistikunternehmen aus Kassel hat ein Jahr lang die Vier-Tage-Woche getestet. Das Ergebnis überrascht: Die Produktivität blieb stabil, während die Krankheitstage um ein Viertel zurückgingen. Die Beschäftigten berichten von besserer Vereinbarkeit von Familie und Beruf. Die Geschäftsführung will das Modell nun dauerhaft einführen, allerdings nur für die Verwaltung, im Lager sei der Personalmangel dafür noch zu groß.“\n\nWie hat sich die Produktivität im Test verändert?', 'multiple_choice', '["Sie blieb stabil", "Sie sank deutlich", "Sie stieg um ein Viertel"]'::jsonb, 'Sie blieb stabil', '„Die Produktivität blieb stabil …“', 10, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Pressetext 2, Vier-Tage-Woche im Test:\n\n„Ein Logistikunternehmen aus Kassel hat ein Jahr lang die Vier-Tage-Woche getestet. Das Ergebnis überrascht: Die Produktivität blieb stabil, während die Krankheitstage um ein Viertel zurückgingen. Die Beschäftigten berichten von besserer Vereinbarkeit von Familie und Beruf. Die Geschäftsführung will das Modell nun dauerhaft einführen, allerdings nur für die Verwaltung, im Lager sei der Personalmangel dafür noch zu groß.“\n\nWas ging um ein Viertel zurück?', 'multiple_choice', '["Die Krankheitstage", "Die Gehälter", "Die Aufträge"]'::jsonb, 'Die Krankheitstage', '„… während die Krankheitstage um ein Viertel zurückgingen.“', 11, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Pressetext 2, Vier-Tage-Woche im Test:\n\n„Ein Logistikunternehmen aus Kassel hat ein Jahr lang die Vier-Tage-Woche getestet. Das Ergebnis überrascht: Die Produktivität blieb stabil, während die Krankheitstage um ein Viertel zurückgingen. Die Beschäftigten berichten von besserer Vereinbarkeit von Familie und Beruf. Die Geschäftsführung will das Modell nun dauerhaft einführen, allerdings nur für die Verwaltung, im Lager sei der Personalmangel dafür noch zu groß.“\n\nFür wen soll das Modell dauerhaft gelten?', 'multiple_choice', '["Nur für die Verwaltung", "Für alle Beschäftigten", "Nur für das Lager"]'::jsonb, 'Nur für die Verwaltung', '„… allerdings nur für die Verwaltung …“', 12, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Anzeigen:\na) Deutschkurs B1–B2, Abendkurs online, zweimal pro Woche\nb) WG-Zimmer nahe Klinikum, 380 € warm, ab sofort\nc) Umzugshelfer mit Transporter, auch am Wochenende\nd) Gebrauchte Fahrräder, geprüfte Qualität, günstig\ne) Steuerberatung für internationale Fachkräfte, Erstgespräch kostenlos\nf) Fitnessstudio 24/7, Probemonat gratis\ng) Kinderbetreuung am Nachmittag, erfahrene Tagesmutter\nh) Kostenlose Anerkennungsberatung für Pflegeabschlüsse\ni) Mitfahrgelegenheit Hamburg–Berlin, jeden Freitag\nj) Second-Hand-Möbel, Lieferung möglich\n\nHinweis: Jede Anzeige passt nur einmal. Für eine Situation gibt es keine passende Anzeige.\n\nSituation 13: Sie ziehen am Samstag um und brauchen Hilfe mit einem Transporter.\n\nWelche Anzeige passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "Keine Anzeige passt"]'::jsonb, 'c', 'Anzeige c bietet Umzugshilfe mit Transporter auch am Wochenende.', 13, 3, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Anzeigen:\na) Deutschkurs B1–B2, Abendkurs online, zweimal pro Woche\nb) WG-Zimmer nahe Klinikum, 380 € warm, ab sofort\nc) Umzugshelfer mit Transporter, auch am Wochenende\nd) Gebrauchte Fahrräder, geprüfte Qualität, günstig\ne) Steuerberatung für internationale Fachkräfte, Erstgespräch kostenlos\nf) Fitnessstudio 24/7, Probemonat gratis\ng) Kinderbetreuung am Nachmittag, erfahrene Tagesmutter\nh) Kostenlose Anerkennungsberatung für Pflegeabschlüsse\ni) Mitfahrgelegenheit Hamburg–Berlin, jeden Freitag\nj) Second-Hand-Möbel, Lieferung möglich\n\nHinweis: Jede Anzeige passt nur einmal. Für eine Situation gibt es keine passende Anzeige.\n\nSituation 14: Eine Pflegekraft möchte ihren ausländischen Abschluss anerkennen lassen.\n\nWelche Anzeige passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "Keine Anzeige passt"]'::jsonb, 'h', 'Anzeige h bietet kostenlose Anerkennungsberatung für Pflegeabschlüsse.', 14, 3, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Anzeigen:\na) Deutschkurs B1–B2, Abendkurs online, zweimal pro Woche\nb) WG-Zimmer nahe Klinikum, 380 € warm, ab sofort\nc) Umzugshelfer mit Transporter, auch am Wochenende\nd) Gebrauchte Fahrräder, geprüfte Qualität, günstig\ne) Steuerberatung für internationale Fachkräfte, Erstgespräch kostenlos\nf) Fitnessstudio 24/7, Probemonat gratis\ng) Kinderbetreuung am Nachmittag, erfahrene Tagesmutter\nh) Kostenlose Anerkennungsberatung für Pflegeabschlüsse\ni) Mitfahrgelegenheit Hamburg–Berlin, jeden Freitag\nj) Second-Hand-Möbel, Lieferung möglich\n\nHinweis: Jede Anzeige passt nur einmal. Für eine Situation gibt es keine passende Anzeige.\n\nSituation 15: Sie fangen im Klinikum an und suchen ein günstiges Zimmer in der Nähe.\n\nWelche Anzeige passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "Keine Anzeige passt"]'::jsonb, 'b', 'Anzeige b: WG-Zimmer nahe Klinikum.', 15, 3, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Anzeigen:\na) Deutschkurs B1–B2, Abendkurs online, zweimal pro Woche\nb) WG-Zimmer nahe Klinikum, 380 € warm, ab sofort\nc) Umzugshelfer mit Transporter, auch am Wochenende\nd) Gebrauchte Fahrräder, geprüfte Qualität, günstig\ne) Steuerberatung für internationale Fachkräfte, Erstgespräch kostenlos\nf) Fitnessstudio 24/7, Probemonat gratis\ng) Kinderbetreuung am Nachmittag, erfahrene Tagesmutter\nh) Kostenlose Anerkennungsberatung für Pflegeabschlüsse\ni) Mitfahrgelegenheit Hamburg–Berlin, jeden Freitag\nj) Second-Hand-Möbel, Lieferung möglich\n\nHinweis: Jede Anzeige passt nur einmal. Für eine Situation gibt es keine passende Anzeige.\n\nSituation 16: Sie brauchen nachmittags Betreuung für Ihre Tochter.\n\nWelche Anzeige passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "Keine Anzeige passt"]'::jsonb, 'g', 'Anzeige g: Kinderbetreuung am Nachmittag.', 16, 3, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Anzeigen:\na) Deutschkurs B1–B2, Abendkurs online, zweimal pro Woche\nb) WG-Zimmer nahe Klinikum, 380 € warm, ab sofort\nc) Umzugshelfer mit Transporter, auch am Wochenende\nd) Gebrauchte Fahrräder, geprüfte Qualität, günstig\ne) Steuerberatung für internationale Fachkräfte, Erstgespräch kostenlos\nf) Fitnessstudio 24/7, Probemonat gratis\ng) Kinderbetreuung am Nachmittag, erfahrene Tagesmutter\nh) Kostenlose Anerkennungsberatung für Pflegeabschlüsse\ni) Mitfahrgelegenheit Hamburg–Berlin, jeden Freitag\nj) Second-Hand-Möbel, Lieferung möglich\n\nHinweis: Jede Anzeige passt nur einmal. Für eine Situation gibt es keine passende Anzeige.\n\nSituation 17: Sie möchten günstig ein gebrauchtes Fahrrad kaufen.\n\nWelche Anzeige passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "Keine Anzeige passt"]'::jsonb, 'd', 'Anzeige d: gebrauchte Fahrräder.', 17, 3, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Anzeigen:\na) Deutschkurs B1–B2, Abendkurs online, zweimal pro Woche\nb) WG-Zimmer nahe Klinikum, 380 € warm, ab sofort\nc) Umzugshelfer mit Transporter, auch am Wochenende\nd) Gebrauchte Fahrräder, geprüfte Qualität, günstig\ne) Steuerberatung für internationale Fachkräfte, Erstgespräch kostenlos\nf) Fitnessstudio 24/7, Probemonat gratis\ng) Kinderbetreuung am Nachmittag, erfahrene Tagesmutter\nh) Kostenlose Anerkennungsberatung für Pflegeabschlüsse\ni) Mitfahrgelegenheit Hamburg–Berlin, jeden Freitag\nj) Second-Hand-Möbel, Lieferung möglich\n\nHinweis: Jede Anzeige passt nur einmal. Für eine Situation gibt es keine passende Anzeige.\n\nSituation 18: Sie fahren jeden Freitag von Hamburg nach Berlin und suchen eine günstige Verbindung.\n\nWelche Anzeige passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "Keine Anzeige passt"]'::jsonb, 'i', 'Anzeige i: Mitfahrgelegenheit Hamburg–Berlin jeden Freitag.', 18, 3, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Anzeigen:\na) Deutschkurs B1–B2, Abendkurs online, zweimal pro Woche\nb) WG-Zimmer nahe Klinikum, 380 € warm, ab sofort\nc) Umzugshelfer mit Transporter, auch am Wochenende\nd) Gebrauchte Fahrräder, geprüfte Qualität, günstig\ne) Steuerberatung für internationale Fachkräfte, Erstgespräch kostenlos\nf) Fitnessstudio 24/7, Probemonat gratis\ng) Kinderbetreuung am Nachmittag, erfahrene Tagesmutter\nh) Kostenlose Anerkennungsberatung für Pflegeabschlüsse\ni) Mitfahrgelegenheit Hamburg–Berlin, jeden Freitag\nj) Second-Hand-Möbel, Lieferung möglich\n\nHinweis: Jede Anzeige passt nur einmal. Für eine Situation gibt es keine passende Anzeige.\n\nSituation 19: Sie haben Streit mit Ihrem Vermieter und suchen rechtliche Hilfe im Mietrecht.\n\nWelche Anzeige passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "Keine Anzeige passt"]'::jsonb, 'Keine Anzeige passt', 'Keine der Anzeigen bietet Rechtsberatung im Mietrecht an.', 19, 3, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Sollte private Handynutzung am Arbeitsplatz verboten werden?\n\nIst die Person für ein Verbot?\n\nJonas: „Ständig schauen Kollegen auf ihr Handy statt zu arbeiten. Ein klares Verbot wäre ehrlich gesagt die einfachste Lösung.“', 'multiple_choice', '["Ja", "Nein"]'::jsonb, 'Ja', 'Jonas nennt ein Verbot „die einfachste Lösung“, er ist dafür.', 20, 4, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Sollte private Handynutzung am Arbeitsplatz verboten werden?\n\nIst die Person für ein Verbot?\n\nAmina: „Ich habe zwei Kinder in der Schule. Wenn etwas passiert, muss ich erreichbar sein, ein Verbot wäre für Eltern unzumutbar.“', 'multiple_choice', '["Ja", "Nein"]'::jsonb, 'Nein', 'Amina hält ein Verbot für „unzumutbar“, sie ist dagegen.', 21, 4, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Sollte private Handynutzung am Arbeitsplatz verboten werden?\n\nIst die Person für ein Verbot?\n\nPavel: „In der Produktion ist ein Handy eine echte Unfallgefahr. Bei uns hat es deshalb nichts zu suchen, da bin ich streng.“', 'multiple_choice', '["Ja", "Nein"]'::jsonb, 'Ja', 'Pavel sagt, das Handy habe am Arbeitsplatz „nichts zu suchen“, er ist dafür.', 22, 4, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Sollte private Handynutzung am Arbeitsplatz verboten werden?\n\nIst die Person für ein Verbot?\n\nGrace: „Erwachsene Menschen brauchen keine Verbote, sondern Vertrauen. Wer seine Arbeit schafft, soll auch mal aufs Handy schauen dürfen.“', 'multiple_choice', '["Ja", "Nein"]'::jsonb, 'Nein', 'Grace setzt auf Vertrauen statt Verbote, sie ist dagegen.', 23, 4, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Sollte private Handynutzung am Arbeitsplatz verboten werden?\n\nIst die Person für ein Verbot?\n\nMurat: „Wir haben eine einfache Regel: in Pausen erlaubt, sonst nicht. Ein komplettes Verbot halte ich für übertrieben.“', 'multiple_choice', '["Ja", "Nein"]'::jsonb, 'Nein', 'Murat hält ein komplettes Verbot für „übertrieben“, er ist dagegen.', 24, 4, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Sollte private Handynutzung am Arbeitsplatz verboten werden?\n\nIst die Person für ein Verbot?\n\nHelene: „Seit unser Chef Handys in Besprechungen verboten hat, sind wir doppelt so schnell fertig. Ich würde das Verbot sofort ausweiten.“', 'multiple_choice', '["Ja", "Nein"]'::jsonb, 'Ja', 'Helene würde das Verbot „sofort ausweiten“, sie ist dafür.', 25, 4, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Sollte private Handynutzung am Arbeitsplatz verboten werden?\n\nIst die Person für ein Verbot?\n\nTobias: „Mein Handy ist mein Arbeitswerkzeug, Dienstplan, Fachartikel, Übersetzer. Ein Verbot würde meine Arbeit schlechter machen.“', 'multiple_choice', '["Ja", "Nein"]'::jsonb, 'Nein', 'Für Tobias ist das Handy ein Arbeitswerkzeug, er ist gegen ein Verbot.', 26, 4, 'true_false', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Betriebsvereinbarung Schichtdienst (Auszug):\n\n„§3 Dienstplan: Der Dienstplan wird jeweils am 15. des Vormonats veröffentlicht. Tauschwünsche sind bis spätestens 72 Stunden vor Schichtbeginn mit der Schichtleitung abzustimmen. §5 Krankmeldung: Erkrankte Beschäftigte informieren die Station telefonisch vor Schichtbeginn; eine ärztliche Bescheinigung ist ab dem dritten Kalendertag vorzulegen. §8 Fortbildung: Pro Kalenderjahr besteht Anspruch auf fünf bezahlte Fortbildungstage. Der Antrag ist mindestens vier Wochen im Voraus zu stellen.“\n\nWann wird der Dienstplan veröffentlicht?', 'multiple_choice', '["Am 15. des Vormonats", "Am Monatsersten", "Eine Woche vor Monatsbeginn"]'::jsonb, 'Am 15. des Vormonats', '§3: „… am 15. des Vormonats veröffentlicht.“', 27, 5, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Betriebsvereinbarung Schichtdienst (Auszug):\n\n„§3 Dienstplan: Der Dienstplan wird jeweils am 15. des Vormonats veröffentlicht. Tauschwünsche sind bis spätestens 72 Stunden vor Schichtbeginn mit der Schichtleitung abzustimmen. §5 Krankmeldung: Erkrankte Beschäftigte informieren die Station telefonisch vor Schichtbeginn; eine ärztliche Bescheinigung ist ab dem dritten Kalendertag vorzulegen. §8 Fortbildung: Pro Kalenderjahr besteht Anspruch auf fünf bezahlte Fortbildungstage. Der Antrag ist mindestens vier Wochen im Voraus zu stellen.“\n\nBis wann müssen Tauschwünsche abgestimmt sein?', 'multiple_choice', '["72 Stunden vor Schichtbeginn", "24 Stunden vor Schichtbeginn", "Eine Woche vor Schichtbeginn"]'::jsonb, '72 Stunden vor Schichtbeginn', '§3: „… bis spätestens 72 Stunden vor Schichtbeginn …“', 28, 5, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Betriebsvereinbarung Schichtdienst (Auszug):\n\n„§3 Dienstplan: Der Dienstplan wird jeweils am 15. des Vormonats veröffentlicht. Tauschwünsche sind bis spätestens 72 Stunden vor Schichtbeginn mit der Schichtleitung abzustimmen. §5 Krankmeldung: Erkrankte Beschäftigte informieren die Station telefonisch vor Schichtbeginn; eine ärztliche Bescheinigung ist ab dem dritten Kalendertag vorzulegen. §8 Fortbildung: Pro Kalenderjahr besteht Anspruch auf fünf bezahlte Fortbildungstage. Der Antrag ist mindestens vier Wochen im Voraus zu stellen.“\n\nAb wann ist eine ärztliche Bescheinigung nötig?', 'multiple_choice', '["Ab dem dritten Kalendertag", "Ab dem ersten Tag", "Erst nach einer Woche"]'::jsonb, 'Ab dem dritten Kalendertag', '§5: „… ab dem dritten Kalendertag vorzulegen.“', 29, 5, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Betriebsvereinbarung Schichtdienst (Auszug):\n\n„§3 Dienstplan: Der Dienstplan wird jeweils am 15. des Vormonats veröffentlicht. Tauschwünsche sind bis spätestens 72 Stunden vor Schichtbeginn mit der Schichtleitung abzustimmen. §5 Krankmeldung: Erkrankte Beschäftigte informieren die Station telefonisch vor Schichtbeginn; eine ärztliche Bescheinigung ist ab dem dritten Kalendertag vorzulegen. §8 Fortbildung: Pro Kalenderjahr besteht Anspruch auf fünf bezahlte Fortbildungstage. Der Antrag ist mindestens vier Wochen im Voraus zu stellen.“\n\nWie viele bezahlte Fortbildungstage stehen pro Jahr zu?', 'multiple_choice', '["Fünf", "Drei", "Zehn"]'::jsonb, 'Fünf', '§8: „… Anspruch auf fünf bezahlte Fortbildungstage.“', 30, 5, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B1' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 1: Wer konnte die Weiterbildung nur dank des Arbeitgebers machen?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'c', 'Ravi: „Ohne diese Unterstützung hätte ich es nicht geschafft.“', 1, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 2: Wer hat auf einen formalen Abschluss verzichtet?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'b', 'Marta hat „ohne formalen Abschluss Verantwortung bekommen“.', 2, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 3: Wer hat durch die Weiterbildung die Branche gewechselt?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'd', 'Nasrin: „… den Wechsel in die IT-Branche ermöglicht.“', 3, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 4: Wer bezeichnet den Verzicht auf Freizeit als lohnende Investition?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'a', 'Chidi: „… die beste Investition meines Lebens.“', 4, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 5: Wer fordert mehr Engagement von den Betrieben?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'c', 'Ravi: „… Betriebe müssten das viel häufiger anbieten.“', 5, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 6: Wer hat hauptsächlich nachts gelernt?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'd', 'Nasrin: „… in meinem eigenen Tempo, meist nachts.“', 6, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 7: Wessen Einkommen hat sich verdoppelt?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'd', 'Nasrin: „… heute verdiene ich das Doppelte.“', 7, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 8: Wer konnte aus familiären Gründen keinen Abendkurs besuchen?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'b', 'Marta: „Mit zwei kleinen Kindern kam ein Abendkurs … nicht infrage.“', 8, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Weiterbildung neben dem Beruf, vier Erfahrungen\n\nPerson a (Chidi): „Ich habe berufsbegleitend einen Meisterkurs gemacht, abends und am Wochenende. Es war anstrengend, aber mein Gehalt ist danach deutlich gestiegen. Rückblickend war der Verzicht auf Freizeit die beste Investition meines Lebens.“\n\nPerson b (Marta): „Mit zwei kleinen Kindern kam ein Abendkurs für mich nicht infrage. Ich habe stattdessen intern jede Chance genutzt, neue Aufgaben zu übernehmen, so habe ich ohne formalen Abschluss Verantwortung bekommen.“\n\nPerson c (Ravi): „Mein Arbeitgeber hat die Fortbildung komplett bezahlt und mir Arbeitszeit dafür freigegeben. Ohne diese Unterstützung hätte ich es nicht geschafft, ich finde, Betriebe müssten das viel häufiger anbieten.“\n\nPerson d (Nasrin): „Ich habe online studiert, in meinem eigenen Tempo, meist nachts. Das war finanziell die einzige Option. Der Abschluss hat mir dann den Wechsel in die IT-Branche ermöglicht, heute verdiene ich das Doppelte.“\n\nAussage 9: Wessen Gehalt stieg nach einem Meisterkurs?\n\nWelche Person passt?', 'multiple_choice', '["a", "b", "c", "d"]'::jsonb, 'a', 'Chidi: „… mein Gehalt ist danach deutlich gestiegen.“', 9, 1, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Sachtext, Anerkennung ausländischer Berufsabschlüsse:\n\n„Wer mit einem ausländischen Berufsabschluss in Deutschland arbeiten will, muss diesen in vielen Fällen anerkennen lassen, bei reglementierten Berufen wie der Pflege ist das sogar zwingend. Die Verfahren dauern offiziell drei Monate, in der Praxis vergehen jedoch oft mehr als acht, weil Unterlagen nachgefordert werden und Übersetzungen fehlen. Eine Studie des Instituts für Arbeitsmarktforschung beziffert die Kosten für Antragstellende auf durchschnittlich 600 Euro. Immerhin: Wer das Verfahren abschließt, verdient nach fünf Jahren im Schnitt so viel wie einheimische Fachkräfte. Expertinnen fordern deshalb, Antragstellende früh zu beraten und die Verfahren zu digitalisieren, statt sie durch immer neue Nachweispflichten zu verlängern.“\n\nBei welchen Berufen ist die Anerkennung zwingend erforderlich?', 'multiple_choice', '["Bei reglementierten Berufen wie der Pflege", "Bei allen Berufen", "Nur bei akademischen Berufen"]'::jsonb, 'Bei reglementierten Berufen wie der Pflege', '„… bei reglementierten Berufen wie der Pflege ist das sogar zwingend.“', 10, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Sachtext, Anerkennung ausländischer Berufsabschlüsse:\n\n„Wer mit einem ausländischen Berufsabschluss in Deutschland arbeiten will, muss diesen in vielen Fällen anerkennen lassen, bei reglementierten Berufen wie der Pflege ist das sogar zwingend. Die Verfahren dauern offiziell drei Monate, in der Praxis vergehen jedoch oft mehr als acht, weil Unterlagen nachgefordert werden und Übersetzungen fehlen. Eine Studie des Instituts für Arbeitsmarktforschung beziffert die Kosten für Antragstellende auf durchschnittlich 600 Euro. Immerhin: Wer das Verfahren abschließt, verdient nach fünf Jahren im Schnitt so viel wie einheimische Fachkräfte. Expertinnen fordern deshalb, Antragstellende früh zu beraten und die Verfahren zu digitalisieren, statt sie durch immer neue Nachweispflichten zu verlängern.“\n\nWarum dauern die Verfahren in der Praxis länger als offiziell vorgesehen?', 'multiple_choice', '["Weil Unterlagen nachgefordert werden und Übersetzungen fehlen", "Weil zu wenige Anträge gestellt werden", "Weil die Gebühren zu niedrig sind"]'::jsonb, 'Weil Unterlagen nachgefordert werden und Übersetzungen fehlen', '„… weil Unterlagen nachgefordert werden und Übersetzungen fehlen.“', 11, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Sachtext, Anerkennung ausländischer Berufsabschlüsse:\n\n„Wer mit einem ausländischen Berufsabschluss in Deutschland arbeiten will, muss diesen in vielen Fällen anerkennen lassen, bei reglementierten Berufen wie der Pflege ist das sogar zwingend. Die Verfahren dauern offiziell drei Monate, in der Praxis vergehen jedoch oft mehr als acht, weil Unterlagen nachgefordert werden und Übersetzungen fehlen. Eine Studie des Instituts für Arbeitsmarktforschung beziffert die Kosten für Antragstellende auf durchschnittlich 600 Euro. Immerhin: Wer das Verfahren abschließt, verdient nach fünf Jahren im Schnitt so viel wie einheimische Fachkräfte. Expertinnen fordern deshalb, Antragstellende früh zu beraten und die Verfahren zu digitalisieren, statt sie durch immer neue Nachweispflichten zu verlängern.“\n\nWie hoch sind die durchschnittlichen Kosten laut Studie?', 'multiple_choice', '["600 Euro", "300 Euro", "1.000 Euro"]'::jsonb, '600 Euro', '„… auf durchschnittlich 600 Euro.“', 12, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Sachtext, Anerkennung ausländischer Berufsabschlüsse:\n\n„Wer mit einem ausländischen Berufsabschluss in Deutschland arbeiten will, muss diesen in vielen Fällen anerkennen lassen, bei reglementierten Berufen wie der Pflege ist das sogar zwingend. Die Verfahren dauern offiziell drei Monate, in der Praxis vergehen jedoch oft mehr als acht, weil Unterlagen nachgefordert werden und Übersetzungen fehlen. Eine Studie des Instituts für Arbeitsmarktforschung beziffert die Kosten für Antragstellende auf durchschnittlich 600 Euro. Immerhin: Wer das Verfahren abschließt, verdient nach fünf Jahren im Schnitt so viel wie einheimische Fachkräfte. Expertinnen fordern deshalb, Antragstellende früh zu beraten und die Verfahren zu digitalisieren, statt sie durch immer neue Nachweispflichten zu verlängern.“\n\nWas gilt für das Einkommen nach erfolgreichem Abschluss des Verfahrens?', 'multiple_choice', '["Nach fünf Jahren entspricht es dem einheimischer Fachkräfte", "Es bleibt dauerhaft niedriger", "Es ist sofort höher als das einheimischer Fachkräfte"]'::jsonb, 'Nach fünf Jahren entspricht es dem einheimischer Fachkräfte', '„… verdient nach fünf Jahren im Schnitt so viel wie einheimische Fachkräfte.“', 13, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Sachtext, Anerkennung ausländischer Berufsabschlüsse:\n\n„Wer mit einem ausländischen Berufsabschluss in Deutschland arbeiten will, muss diesen in vielen Fällen anerkennen lassen, bei reglementierten Berufen wie der Pflege ist das sogar zwingend. Die Verfahren dauern offiziell drei Monate, in der Praxis vergehen jedoch oft mehr als acht, weil Unterlagen nachgefordert werden und Übersetzungen fehlen. Eine Studie des Instituts für Arbeitsmarktforschung beziffert die Kosten für Antragstellende auf durchschnittlich 600 Euro. Immerhin: Wer das Verfahren abschließt, verdient nach fünf Jahren im Schnitt so viel wie einheimische Fachkräfte. Expertinnen fordern deshalb, Antragstellende früh zu beraten und die Verfahren zu digitalisieren, statt sie durch immer neue Nachweispflichten zu verlängern.“\n\nWas fordern Expertinnen?', 'multiple_choice', '["Frühe Beratung und digitale Verfahren", "Höhere Gebühren", "Mehr Nachweispflichten"]'::jsonb, 'Frühe Beratung und digitale Verfahren', '„… früh zu beraten und die Verfahren zu digitalisieren …“', 14, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Sachtext, Anerkennung ausländischer Berufsabschlüsse:\n\n„Wer mit einem ausländischen Berufsabschluss in Deutschland arbeiten will, muss diesen in vielen Fällen anerkennen lassen, bei reglementierten Berufen wie der Pflege ist das sogar zwingend. Die Verfahren dauern offiziell drei Monate, in der Praxis vergehen jedoch oft mehr als acht, weil Unterlagen nachgefordert werden und Übersetzungen fehlen. Eine Studie des Instituts für Arbeitsmarktforschung beziffert die Kosten für Antragstellende auf durchschnittlich 600 Euro. Immerhin: Wer das Verfahren abschließt, verdient nach fünf Jahren im Schnitt so viel wie einheimische Fachkräfte. Expertinnen fordern deshalb, Antragstellende früh zu beraten und die Verfahren zu digitalisieren, statt sie durch immer neue Nachweispflichten zu verlängern.“\n\nWelche Haltung nimmt der Text zu neuen Nachweispflichten ein?', 'multiple_choice', '["Eine ablehnende", "Eine zustimmende", "Keine erkennbare"]'::jsonb, 'Eine ablehnende', '„… statt sie durch immer neue Nachweispflichten zu verlängern“ signalisiert Kritik.', 15, 2, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Reportage, Simulation statt Stationsalltag?\n\n„Im Skills-Lab der Pflegeschule Bochum piepsen Monitore, doch der Patient ist eine Puppe: Auszubildende trainieren hier Notfälle, die im echten Stationsalltag zum Glück selten sind. Studienleiterin Dr. Weber sieht darin einen doppelten Vorteil: Fehler haben keine Folgen, und jede Übung lässt sich beliebig wiederholen. Kritik kommt von Praxisanleitern: Die Puppe stelle keine Fragen und habe keine Angst, wer nur simuliere, lerne den Umgang mit echten Menschen nicht. Die Schule reagiert darauf mit einem Mischmodell: Auf jede Simulationswoche folgen drei Wochen Praxiseinsatz. Erste Auswertungen zeigen, dass die Absolventen des Mischmodells in Prüfungen sicherer handeln, sich aber genauso oft überfordert fühlen wie früher, wenn Angehörige emotional reagieren.“\n\nWas ist der Hauptvorteil der Simulation laut Dr. Weber?', 'multiple_choice', '["Fehler bleiben folgenlos und Übungen sind wiederholbar", "Die Ausbildung wird billiger", "Die Auszubildenden brauchen keine Praxis mehr"]'::jsonb, 'Fehler bleiben folgenlos und Übungen sind wiederholbar', '„Fehler haben keine Folgen, und jede Übung lässt sich beliebig wiederholen.“', 16, 3, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Reportage, Simulation statt Stationsalltag?\n\n„Im Skills-Lab der Pflegeschule Bochum piepsen Monitore, doch der Patient ist eine Puppe: Auszubildende trainieren hier Notfälle, die im echten Stationsalltag zum Glück selten sind. Studienleiterin Dr. Weber sieht darin einen doppelten Vorteil: Fehler haben keine Folgen, und jede Übung lässt sich beliebig wiederholen. Kritik kommt von Praxisanleitern: Die Puppe stelle keine Fragen und habe keine Angst, wer nur simuliere, lerne den Umgang mit echten Menschen nicht. Die Schule reagiert darauf mit einem Mischmodell: Auf jede Simulationswoche folgen drei Wochen Praxiseinsatz. Erste Auswertungen zeigen, dass die Absolventen des Mischmodells in Prüfungen sicherer handeln, sich aber genauso oft überfordert fühlen wie früher, wenn Angehörige emotional reagieren.“\n\nWas kritisieren die Praxisanleiter?', 'multiple_choice', '["Simulation ersetze nicht den Umgang mit echten Menschen", "Die Technik sei zu teuer", "Die Puppen seien zu realistisch"]'::jsonb, 'Simulation ersetze nicht den Umgang mit echten Menschen', '„… wer nur simuliere, lerne den Umgang mit echten Menschen nicht.“', 17, 3, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Reportage, Simulation statt Stationsalltag?\n\n„Im Skills-Lab der Pflegeschule Bochum piepsen Monitore, doch der Patient ist eine Puppe: Auszubildende trainieren hier Notfälle, die im echten Stationsalltag zum Glück selten sind. Studienleiterin Dr. Weber sieht darin einen doppelten Vorteil: Fehler haben keine Folgen, und jede Übung lässt sich beliebig wiederholen. Kritik kommt von Praxisanleitern: Die Puppe stelle keine Fragen und habe keine Angst, wer nur simuliere, lerne den Umgang mit echten Menschen nicht. Die Schule reagiert darauf mit einem Mischmodell: Auf jede Simulationswoche folgen drei Wochen Praxiseinsatz. Erste Auswertungen zeigen, dass die Absolventen des Mischmodells in Prüfungen sicherer handeln, sich aber genauso oft überfordert fühlen wie früher, wenn Angehörige emotional reagieren.“\n\nWie reagiert die Schule auf die Kritik?', 'multiple_choice', '["Mit einem Mischmodell aus Simulation und Praxis", "Mit mehr Simulationswochen", "Mit dem Ende des Skills-Labs"]'::jsonb, 'Mit einem Mischmodell aus Simulation und Praxis', '„Auf jede Simulationswoche folgen drei Wochen Praxiseinsatz.“', 18, 3, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Reportage, Simulation statt Stationsalltag?\n\n„Im Skills-Lab der Pflegeschule Bochum piepsen Monitore, doch der Patient ist eine Puppe: Auszubildende trainieren hier Notfälle, die im echten Stationsalltag zum Glück selten sind. Studienleiterin Dr. Weber sieht darin einen doppelten Vorteil: Fehler haben keine Folgen, und jede Übung lässt sich beliebig wiederholen. Kritik kommt von Praxisanleitern: Die Puppe stelle keine Fragen und habe keine Angst, wer nur simuliere, lerne den Umgang mit echten Menschen nicht. Die Schule reagiert darauf mit einem Mischmodell: Auf jede Simulationswoche folgen drei Wochen Praxiseinsatz. Erste Auswertungen zeigen, dass die Absolventen des Mischmodells in Prüfungen sicherer handeln, sich aber genauso oft überfordert fühlen wie früher, wenn Angehörige emotional reagieren.“\n\nWorin sind Absolventen des Mischmodells besser?', 'multiple_choice', '["Sie handeln in Prüfungen sicherer", "Sie fühlen sich nie überfordert", "Sie arbeiten schneller am Computer"]'::jsonb, 'Sie handeln in Prüfungen sicherer', '„… in Prüfungen sicherer handeln …“', 19, 3, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Reportage, Simulation statt Stationsalltag?\n\n„Im Skills-Lab der Pflegeschule Bochum piepsen Monitore, doch der Patient ist eine Puppe: Auszubildende trainieren hier Notfälle, die im echten Stationsalltag zum Glück selten sind. Studienleiterin Dr. Weber sieht darin einen doppelten Vorteil: Fehler haben keine Folgen, und jede Übung lässt sich beliebig wiederholen. Kritik kommt von Praxisanleitern: Die Puppe stelle keine Fragen und habe keine Angst, wer nur simuliere, lerne den Umgang mit echten Menschen nicht. Die Schule reagiert darauf mit einem Mischmodell: Auf jede Simulationswoche folgen drei Wochen Praxiseinsatz. Erste Auswertungen zeigen, dass die Absolventen des Mischmodells in Prüfungen sicherer handeln, sich aber genauso oft überfordert fühlen wie früher, wenn Angehörige emotional reagieren.“\n\nWobei fühlen sich Absolventen weiterhin überfordert?', 'multiple_choice', '["Wenn Angehörige emotional reagieren", "Bei technischen Notfällen", "Bei schriftlichen Prüfungen"]'::jsonb, 'Wenn Angehörige emotional reagieren', '„… wenn Angehörige emotional reagieren.“', 20, 3, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Reportage, Simulation statt Stationsalltag?\n\n„Im Skills-Lab der Pflegeschule Bochum piepsen Monitore, doch der Patient ist eine Puppe: Auszubildende trainieren hier Notfälle, die im echten Stationsalltag zum Glück selten sind. Studienleiterin Dr. Weber sieht darin einen doppelten Vorteil: Fehler haben keine Folgen, und jede Übung lässt sich beliebig wiederholen. Kritik kommt von Praxisanleitern: Die Puppe stelle keine Fragen und habe keine Angst, wer nur simuliere, lerne den Umgang mit echten Menschen nicht. Die Schule reagiert darauf mit einem Mischmodell: Auf jede Simulationswoche folgen drei Wochen Praxiseinsatz. Erste Auswertungen zeigen, dass die Absolventen des Mischmodells in Prüfungen sicherer handeln, sich aber genauso oft überfordert fühlen wie früher, wenn Angehörige emotional reagieren.“\n\nWelche Aussage entspricht dem Gesamttenor des Textes?', 'multiple_choice', '["Simulation ist nützlich, ersetzt aber die Praxis nicht", "Simulation ist überflüssig", "Praxiseinsätze sollten abgeschafft werden"]'::jsonb, 'Simulation ist nützlich, ersetzt aber die Praxis nicht', 'Der Text stellt Vorteile und Grenzen der Simulation gegenüber.', 21, 3, 'mcq', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Arbeiten im Homeoffice, Stimmen aus einem Forum\n\nÄußerungen:\na) „Ohne stabiles Internet und einen zweiten Bildschirm hätte ich zu Hause keine Chance, produktiv zu sein.“\nb) „Mir fehlen die Gespräche in der Kaffeeküche, nach drei Wochen allein zu Hause fällt mir die Decke auf den Kopf.“\nc) „Ich bringe morgens die Kinder zur Schule und setze mich danach an den Schreibtisch, das ginge im Büro nie.“\nd) „Zu Hause lauern überall Ablenkungen. Man muss sich feste Zeiten setzen, sonst wird das nichts.“\ne) „Allein das gesparte Bahnticket macht bei mir über 100 Euro im Monat aus.“\nf) „Unser Team hat vereinbart, wann jeder erreichbar ist, seitdem gibt es kaum noch Missverständnisse.“\ng) „Ich vermisse es, mich für die Arbeit schick anzuziehen, in Jogginghose fühle ich mich unprofessionell.“\n\nHinweis: Eine Äußerung passt zu keiner Überschrift.\n\nÜberschrift 22: „Technik als Grundvoraussetzung“\n\nWelche Äußerung passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g"]'::jsonb, 'a', 'Äußerung a nennt Internet und Ausstattung als Bedingung.', 22, 4, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Arbeiten im Homeoffice, Stimmen aus einem Forum\n\nÄußerungen:\na) „Ohne stabiles Internet und einen zweiten Bildschirm hätte ich zu Hause keine Chance, produktiv zu sein.“\nb) „Mir fehlen die Gespräche in der Kaffeeküche, nach drei Wochen allein zu Hause fällt mir die Decke auf den Kopf.“\nc) „Ich bringe morgens die Kinder zur Schule und setze mich danach an den Schreibtisch, das ginge im Büro nie.“\nd) „Zu Hause lauern überall Ablenkungen. Man muss sich feste Zeiten setzen, sonst wird das nichts.“\ne) „Allein das gesparte Bahnticket macht bei mir über 100 Euro im Monat aus.“\nf) „Unser Team hat vereinbart, wann jeder erreichbar ist, seitdem gibt es kaum noch Missverständnisse.“\ng) „Ich vermisse es, mich für die Arbeit schick anzuziehen, in Jogginghose fühle ich mich unprofessionell.“\n\nHinweis: Eine Äußerung passt zu keiner Überschrift.\n\nÜberschrift 23: „Gefahr der Vereinsamung“\n\nWelche Äußerung passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g"]'::jsonb, 'b', 'Äußerung b beschreibt fehlende soziale Kontakte.', 23, 4, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Arbeiten im Homeoffice, Stimmen aus einem Forum\n\nÄußerungen:\na) „Ohne stabiles Internet und einen zweiten Bildschirm hätte ich zu Hause keine Chance, produktiv zu sein.“\nb) „Mir fehlen die Gespräche in der Kaffeeküche, nach drei Wochen allein zu Hause fällt mir die Decke auf den Kopf.“\nc) „Ich bringe morgens die Kinder zur Schule und setze mich danach an den Schreibtisch, das ginge im Büro nie.“\nd) „Zu Hause lauern überall Ablenkungen. Man muss sich feste Zeiten setzen, sonst wird das nichts.“\ne) „Allein das gesparte Bahnticket macht bei mir über 100 Euro im Monat aus.“\nf) „Unser Team hat vereinbart, wann jeder erreichbar ist, seitdem gibt es kaum noch Missverständnisse.“\ng) „Ich vermisse es, mich für die Arbeit schick anzuziehen, in Jogginghose fühle ich mich unprofessionell.“\n\nHinweis: Eine Äußerung passt zu keiner Überschrift.\n\nÜberschrift 24: „Flexibilität für Familien“\n\nWelche Äußerung passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g"]'::jsonb, 'c', 'Äußerung c verbindet Kinderbetreuung und Arbeit.', 24, 4, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Arbeiten im Homeoffice, Stimmen aus einem Forum\n\nÄußerungen:\na) „Ohne stabiles Internet und einen zweiten Bildschirm hätte ich zu Hause keine Chance, produktiv zu sein.“\nb) „Mir fehlen die Gespräche in der Kaffeeküche, nach drei Wochen allein zu Hause fällt mir die Decke auf den Kopf.“\nc) „Ich bringe morgens die Kinder zur Schule und setze mich danach an den Schreibtisch, das ginge im Büro nie.“\nd) „Zu Hause lauern überall Ablenkungen. Man muss sich feste Zeiten setzen, sonst wird das nichts.“\ne) „Allein das gesparte Bahnticket macht bei mir über 100 Euro im Monat aus.“\nf) „Unser Team hat vereinbart, wann jeder erreichbar ist, seitdem gibt es kaum noch Missverständnisse.“\ng) „Ich vermisse es, mich für die Arbeit schick anzuziehen, in Jogginghose fühle ich mich unprofessionell.“\n\nHinweis: Eine Äußerung passt zu keiner Überschrift.\n\nÜberschrift 25: „Selbstdisziplin ist gefragt“\n\nWelche Äußerung passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g"]'::jsonb, 'd', 'Äußerung d fordert feste Zeiten gegen Ablenkung.', 25, 4, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Arbeiten im Homeoffice, Stimmen aus einem Forum\n\nÄußerungen:\na) „Ohne stabiles Internet und einen zweiten Bildschirm hätte ich zu Hause keine Chance, produktiv zu sein.“\nb) „Mir fehlen die Gespräche in der Kaffeeküche, nach drei Wochen allein zu Hause fällt mir die Decke auf den Kopf.“\nc) „Ich bringe morgens die Kinder zur Schule und setze mich danach an den Schreibtisch, das ginge im Büro nie.“\nd) „Zu Hause lauern überall Ablenkungen. Man muss sich feste Zeiten setzen, sonst wird das nichts.“\ne) „Allein das gesparte Bahnticket macht bei mir über 100 Euro im Monat aus.“\nf) „Unser Team hat vereinbart, wann jeder erreichbar ist, seitdem gibt es kaum noch Missverständnisse.“\ng) „Ich vermisse es, mich für die Arbeit schick anzuziehen, in Jogginghose fühle ich mich unprofessionell.“\n\nHinweis: Eine Äußerung passt zu keiner Überschrift.\n\nÜberschrift 26: „Finanzielle Entlastung“\n\nWelche Äußerung passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g"]'::jsonb, 'e', 'Äußerung e rechnet die gesparten Fahrtkosten vor.', 26, 4, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Thema: Arbeiten im Homeoffice, Stimmen aus einem Forum\n\nÄußerungen:\na) „Ohne stabiles Internet und einen zweiten Bildschirm hätte ich zu Hause keine Chance, produktiv zu sein.“\nb) „Mir fehlen die Gespräche in der Kaffeeküche, nach drei Wochen allein zu Hause fällt mir die Decke auf den Kopf.“\nc) „Ich bringe morgens die Kinder zur Schule und setze mich danach an den Schreibtisch, das ginge im Büro nie.“\nd) „Zu Hause lauern überall Ablenkungen. Man muss sich feste Zeiten setzen, sonst wird das nichts.“\ne) „Allein das gesparte Bahnticket macht bei mir über 100 Euro im Monat aus.“\nf) „Unser Team hat vereinbart, wann jeder erreichbar ist, seitdem gibt es kaum noch Missverständnisse.“\ng) „Ich vermisse es, mich für die Arbeit schick anzuziehen, in Jogginghose fühle ich mich unprofessionell.“\n\nHinweis: Eine Äußerung passt zu keiner Überschrift.\n\nÜberschrift 27: „Klare Absprachen im Team“\n\nWelche Äußerung passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g"]'::jsonb, 'f', 'Äußerung f beschreibt vereinbarte Erreichbarkeit.', 27, 4, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Auszug aus einem Arbeitsvertrag, Inhaltsverzeichnis:\na) Vergütung und Zulagen\nb) Arbeitszeit und Überstunden\nc) Urlaub\nd) Verschwiegenheitspflicht\ne) Kündigungsfristen\nf) Probezeit\ng) Betriebliche Altersvorsorge\nh) Nebentätigkeiten\n\nHinweis: Nicht alle Überschriften werden gebraucht.\n\nParagraf 28: „Die ersten sechs Monate des Arbeitsverhältnisses gelten als Erprobung; in dieser Zeit kann der Vertrag beiderseits mit einer Frist von zwei Wochen beendet werden.“\n\nWelche Überschrift passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h"]'::jsonb, 'f', 'Es geht um die Erprobungszeit zu Beginn, Überschrift f (Probezeit).', 28, 5, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Auszug aus einem Arbeitsvertrag, Inhaltsverzeichnis:\na) Vergütung und Zulagen\nb) Arbeitszeit und Überstunden\nc) Urlaub\nd) Verschwiegenheitspflicht\ne) Kündigungsfristen\nf) Probezeit\ng) Betriebliche Altersvorsorge\nh) Nebentätigkeiten\n\nHinweis: Nicht alle Überschriften werden gebraucht.\n\nParagraf 29: „Über alle Geschäfts- und Betriebsgeheimnisse ist Stillschweigen zu bewahren, auch nach dem Ende des Arbeitsverhältnisses.“\n\nWelche Überschrift passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h"]'::jsonb, 'd', 'Stillschweigen über Geheimnisse, Überschrift d (Verschwiegenheitspflicht).', 29, 5, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';

INSERT INTO questions (test_module_id, question_text, question_type, options, correct_answer, explanation, "order", exam_part, task_type, points)
SELECT tm.id, E'Auszug aus einem Arbeitsvertrag, Inhaltsverzeichnis:\na) Vergütung und Zulagen\nb) Arbeitszeit und Überstunden\nc) Urlaub\nd) Verschwiegenheitspflicht\ne) Kündigungsfristen\nf) Probezeit\ng) Betriebliche Altersvorsorge\nh) Nebentätigkeiten\n\nHinweis: Nicht alle Überschriften werden gebraucht.\n\nParagraf 30: „Die Aufnahme einer entgeltlichen Tätigkeit für einen anderen Arbeitgeber bedarf der vorherigen schriftlichen Zustimmung.“\n\nWelche Überschrift passt?', 'multiple_choice', '["a", "b", "c", "d", "e", "f", "g", "h"]'::jsonb, 'h', 'Tätigkeit für andere Arbeitgeber, Überschrift h (Nebentätigkeiten).', 30, 5, 'matching', 1
FROM test_modules tm JOIN levels l ON tm.level_id = l.id JOIN skills s ON tm.skill_id = s.id
WHERE l.code = 'B2' AND s.code = 'reading';
